name: Hello World JS CI

on:
  push:
    branches:
      - main

jobs:
  run-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Ejecutar el script Hello World
        run: node path/to/hello.js

